# Generated by Django 4.2.2 on 2023-09-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Despesas', 'Despesa'), ('Receita', 'Receita')], max_length=10),
        ),
    ]
